name: desafio_1
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
   path: ^1.8.0
   dio: ^4.0.6
   http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
